#!/usr/bin/env node

const lines = [
  "ui-test command guide",
  "",
  "Basic (start here)",
  "  ui-test setup quickstart      First-run install + Chromium provisioning",
  "  ui-test play                      Run YAML tests",
  "  ui-test play --no-start           Run against an already running app",
  "  ui-test play --save-failure-artifacts  Enable failure artifacts",
  "  ui-test play --no-save-failure-artifacts  Disable failure artifacts",
  "  ui-test play --artifacts-dir <path>     Set failure artifact output path",
  "",
  "Intermediate (record workflows)",
  "  ui-test record                    Record a test into YAML",
  "  ui-test list                      List discovered YAML tests",
  "",
  "Advanced (quality improvements)",
  "  ui-test improve <file>            Analyze selector quality (report-only)",
  "  ui-test improve <file> --apply    Apply approved selector improvements",
  "  ui-test improve <file> --apply-assertions  Apply high-confidence assertions",
  "  ui-test improve <file> --assertion-source snapshot-cli  Enable replay + snapshot assertion candidates",
  "  ui-test improve <file> --assertions none|candidates  Choose assertion candidate generation mode",
  "",
  "Maintainer",
  "  npm test                               Framework suite (Vitest)",
  "  npm run test:smoke                     Consumer smoke flow",
  "  npm run test:coverage                  Coverage run",
  "",
  "One-off fallback",
  "  npx -y github:ddv1982/easy-e2e-testing <command>",
  "",
  "More help",
  "  ui-test --help",
  "  ui-test record --help",
  "  ui-test play --help",
  "  ui-test improve --help",
  "  docs/getting-started.md",
  "",
  "Note: V2 target schema only; legacy selector fields are not supported.",
];

process.stdout.write(`${lines.join("\n")}\n`);
