#!/usr/bin/env node

const lines = [
  "ui-test command guide",
  "",
  "Basic (start here)",
  "  npx ui-test setup                     First-run setup (config + Chromium)",
  "  npx ui-test play                      Run YAML tests",
  "  npx ui-test play --no-start           Run against an already running app",
  "  npx ui-test play --save-failure-artifacts  Enable failure artifacts",
  "  npx ui-test play --no-save-failure-artifacts  Disable failure artifacts",
  "  npx ui-test play --artifacts-dir <path>     Set failure artifact output path",
  "",
  "Intermediate (record workflows)",
  "  npx ui-test record                    Record a test into YAML",
  "  npx ui-test list                      List discovered YAML tests",
  "",
  "Advanced (quality improvements)",
  "  npx ui-test improve <file>            Analyze selector quality (report-only)",
  "  npx ui-test improve <file> --apply    Apply approved selector improvements",
  "  npx ui-test improve <file> --apply-assertions  Apply high-confidence assertions",
  "  npx ui-test improve <file> --llm      Enable local Ollama ranking",
  "",
  "Maintainer",
  "  npm test                               Framework suite (Vitest)",
  "  npm run test:smoke                     Consumer smoke flow",
  "  npm run test:coverage                  Coverage run",
  "",
  "More help",
  "  npx ui-test --help",
  "  npx ui-test record --help",
  "  npx ui-test play --help",
  "  npx ui-test improve --help",
  "  docs/getting-started.md",
  "",
  "Note: V2 target schema only; legacy selector fields are not supported.",
];

process.stdout.write(`${lines.join("\n")}\n`);
